:PROPERTIES:
:ID:       7275d710-8ecf-4841-9cc2-4779990dd8eb
:END:
#+title: Circuits and Lab Equipment_PostLAB
#+filetags:Labs

#+options: toc:nil
\newpage

* Questions
1. ~Discuss how you measured the voltage, amperes, and resistance. Where did you take the measurement and why?~
   a. Using the different settings on the given digital multimeter I determined the voltage, current, and resistance by using banana leads on nodes in between each resistor. For measuring the resistance attached to either side of the resistor in question. And with voltage and current I would connect the incoming terminal to the exit terminal on the previous component to measure the drop.
2. ~Perform a percentage error calculation for the resistors measured in the lab and the predicted color code values in the pre-lab. Why are these values, predicted and measured, different?~
   a. Error Calculation
      + \[\frac{Measured - Given}{Measured} = \frac{0.9876k\Omega - 1k\Omega}{0.9876k\Omega}\] = 1.25% Error
      + \[\frac{Measured - Given}{Measured} = \frac{464.230\Omega - 470\Omega}{464.230\Omega}\] = 1.24% Error
      + \[\frac{Measured - Given}{Measured} = \frac{217.774\Omega - 220\Omega}{217.774\Omega}\] = 1.02% Error
   b. The reason they are different is because all resistors have a resistance measured within a percentage range of the given resistance. This can be determined from looking at the colored bands on the resistor.

3. ~Perform a percentage error calculation for the currents and voltages measured in the lab and the calculated values in the lab. Why are these values, calculated and measured, different?~
   a. Error Calculation 470 and 1kOhm in Parallel
      + \[\frac{Measured-Given}{Measured} = \frac{0.006-0.0064}{0.006} = I_{470}Error\] = 7% Error
      + \[\frac{Measured-Given}{Measured} = \frac{2.96-3}{2.96} = V_{470}Error\] = 1% Error
      + \[\frac{Measured-Given}{Measured} = \frac{0.004-0.003}{0.004} = I_{1kOhm}Error\] = 25% Error
      + \[\frac{Measured-Given}{Measured} = \frac{2.96-3}{2.96} = V_{1kOhm}Error\] = 1% Error
   b. Similar to question 2 as a result in the in-exact resistance of our given resistors the measured results will always be slightly different from that of the calculated resistors.

4. ~How was the temperature of the resistor affected during the experiment?~
   a. During this experiment not nearly enoufh current/voltage was running through each resistor for there to be a notable increase in temperature. However, I would assume that there should be at least some small amount of increase. If we were to increase the voltage entering the system, the resistors would almost undoubtedly see a notable increase in temperature.
