:PROPERTIES:
:ID:       f16157e0-4bf3-464d-9e4f-c50ac9d564e6
:END:
#+title: IntentionalUnintentionalInjuries
[[id:c30fa79b-3dee-4b1d-9c40-ae56db421f43][HAHS1511]]
#+filetags: HomeWork

* Prompt 1:
The term “Unintentional Injuries” being used as a replacement for the former, “accident”, is a more recent adaptation towards how we, as a society, want to reframe how we view these events. The basic idea is that the use of the term “accident” has an implication that these events are a result of random chance. That is to say that they are out of our control and completely unavoidable. I feel that this could have a few impacts in regard to how we frame these incidents as a society. However, in my experience we have not been very successful in this change. For the most part, very few people utilize this terminology. Furthermore, I fear that the usage of this terminology can in fact be damaging in some ways. Using terminology that emphasizes that anything and everything is preventable can come dismiss or unvalidate the experience of an individual; that is, sometimes no matter how much you do, unexpected events can still arise. The impact that using the term unintentional injury as opposed to accident I feel has been small. I feel that it has made little difference up through this point. I suggest that we approach this matter differently however. I do think that both words provide valid but different meanings depending on the situation used. By assimilating both words into use; using them in reference to differing situations, I believe would be the most valuable. This provides a more nuanced approach to how we may frame different matters, which could in turn have a positive outlook more frequently.

* Prompt 2:
I do not, necessarily, have any reason to believe that this data isn't true. However, such as any social matter, data/results fluctuate constantly. Am I to say that the data that suggests that 'violent crime has gone down in recent years' is supposed to be telling of some greater trend suggesting that we are entering an era of peace? No. As mentioned, the matter of any social issue is subject to fluctuate from time to time. That means there are periods of time in which violent crime may decrease for a period. Other times, perhaps, the rate of violent crimes will increase. These are typically tied to a variety of /other/ ever changing issues. An endless cycle. Perhaps these changes are a result in societal or political shifts that have taken place in recent years. It is all hard to say in the end. Again, however, I reiterate; I cannot argue that this decrease we have detected is particularly fake. Surprising, maybe, but not outright fake. In regards to strategies that could be used to address the issue of intentional injury/violence I believe there may be someways to approach the matter. I believe that interhuman violence is a matter that will remain constant. That is, it will never truly go away. People will always have conflict, this cannot be avoided. I do believe however that we can change how we treat these matters. For instance, by shifting prisons in to facilities focused on rehabilitation and reassimilation in to society, rather that of glorified cages and continuous punishment.
