:PROPERTIES:
:ID:       f16157e0-4bf3-464d-9e4f-c50ac9d564e6
:END:
#+title: IntentionalUnintentionalInjuries
[[id:c30fa79b-3dee-4b1d-9c40-ae56db421f43][HAHS1511]]
#+filetags: HomeWork

* Prompt 1:
The term “Unintentional Injuries” being used as a replacement for the former, “accident”, is a more recent adaptation towards how we, as a society, want to reframe how we view these events. The basic idea is that the use of the term “accident” has an implication that these events are a result of random chance. That is to say that they are out of our control and completely unavoidable. I feel that this could have a few impacts in regard to how we frame these incidents as a society. However, in my experience we have not been very successful in this change. For the most part, very few people utilize this terminology. Furthermore, I fear that the usage of this terminology can in fact be damaging in some ways. Using terminology that emphasizes that anything and everything is preventable can come dismiss or unvalidate the experience of an individual; that is, sometimes no matter how much you do, unexpected events can still arise. The impact that using the term unintentional injury as opposed to accident I feel has been small. I feel that it has made little difference up through this point.

* Prompt 2:
