:PROPERTIES:
:ID:       e8b80fcc-eec3-40d7-9256-fe010c5be85e
:END:
#+title: JoJu Smart Mirror
#+filetags:Ideas

~The 'JoJu' SmartMirror is a standalone/mountable mirror with a multitude of features geared toward enhancing and optimizing the personal space experience~

* Overview
** Design Concept
- Size: 16"x24" or 20"x30"???????
** Desired Features
+ Information Displayed
  + Welcoming
  + Weather
  + Time
  + Spotify Integration(?)
  + Affirmations/Love Notes: These could be updated by me remotely (*UPDATES COULD BE ROLLED WITH SSH*)
+ Voice Activation(?)
  + Room Automation (lights/mood setting)
  + Answer basic questions
    + Weather
    + Time
    + Traffic time? (research GPS/Map integration for traffic monitoring)
+ [[id:6d0c53ee-6e82-40a5-8892-c6efa79e85d6][iOS App? ]]

* Materials Required
+ Raspberry Pi
+ Monitor(s) {of approriate size}
+ One-Way Glass {of desired size}
+ Probably more...
*** TODO Shopping List
**** TODO Measure Monitor
      + Two-Way mirror: /TwoWayMirrors.com/ $40-$100
      + Frame (cut wood?): $30-$60
      + Infrared Frame????: $80-$200
      + Raspberry-Pi & PowerSupply: *owned*
      + HDMI cables: *owned*
      + Power Strip?: *owned*
      + Cableties/Velcro: $5-$10
                      _Est. Total_: *$75 - $200* (+100-200 more for touch capability)

~Revised a little bit~
      + Mirror ~ 120
      + Frame ~ 30
      + Power/Cables ~30
      + PIR Sensor ~ 12
                      /Total: 152 - 192 (acrylic or glass)/

      + *PIR Sensor*:  give the device functionality to be asleep until walked in front of.
      + *Software (/MagicMirror2/)*: Plug-and-play software that is free and modular. ----- Maybe build own software later based on this as basis?
* Presentation
~One thing I would really like to do is make some sort of video detailing the construction process, but make it kinda funny. Think BasicallyHomeless or Michael Reeves. So a little silly and /overly edited/.~
** Ideas
+ Ominous Raz-Pi edit in the beginning
+ Video journal my progress for B-Roll
+ Apple/tech company style keynote at the end for presenting features. /DEFINITLEY RENT OUT A ROOM AT SCHOOL/
+ Probably pirate some video editing software.
+ Have opening credits (drama - into silly) /Joel presents....for julie....blah blah/
  + fade-in to me in the sunrise on the train tracks (establishing shot)
  + Fast camera pan (blur) into me in my at my desk [begin silly mode] /Hi. I am Joel, a Computer Engineer at JoJu Tech...../

* Progress Journal
** Pre Materials Phase
