:PROPERTIES:
:ID:       e8b80fcc-eec3-40d7-9256-fe010c5be85e
:END:
#+title: JoJu Smart Mirror
#+filetags:Ideas

~The 'JoJu' SmartMirror is a standalone/mountable mirror with a multitude of features geared toward enhancing and optimizing the personal space experience~

* Overview
** Design Concept
- Size: 16"x24" or 20"x30"
** Desired Features
+ Information Displayed
  + Welcoming
  + Weather
  + Time
  + Spotify Integration(?)
  + Affirmations/Love Notes: These could be updated by me remotely
+ Voice Activation
  + Room Automation (lights/mood setting)
  + Answer basic questions
    + Weather
    + Time
    + Traffic time? (research GPS/Map integration for traffic monitoring)
+ [[id:6d0c53ee-6e82-40a5-8892-c6efa79e85d6][iOS App? ]]

* Materials Required
+ Raspberry Pi
+ Monitor(s) {of approriate size}
+ One-Way Glass {of desired size}
+ Probably more...
*** Shopping List: *Definitive*

* Presentation
~One thing I would really like to do is make some sort of video detailing the construction process, but make it kinda funny. Think BasicallyHomeless or Michael Reeves. So a little silly and /overly edited/.~
** Ideas
+ Ominous Raz-Pi edit in the beginning
+ Video journal my progress for B-Roll
+ Apple/tech company style keynote at the end for presenting features. /DEFINITLEY RENT OUT A ROOM AT SCHOOL/
+ Probably pirate some video editing software.
+ Have opening credits (drama - into silly) /Joel presents....for julie....blah blah/
  + fade-in to me in the sunrise on the train tracks (establishing shot)
  + Fast camera pan (blur) into me in my at my desk [begin silly mode] /Hi. I am Joel, a Computer Engineer at JoJu Tech...../

* Progress Journal
