:PROPERTIES:
:ID:       6842c79f-5360-48ed-80b8-5d5e152c1930
:END:
#+title: MentalHealthOverview
[[id:c30fa79b-3dee-4b1d-9c40-ae56db421f43][HAHS1511]]
#+filetags: HomeWork

* Prompt 1
In the slides the DSM5 defines mental illness as a “a mental disorder is a syndrome characterized by clinically significant disturbance in an individual's cognition, emotion regulation, or behavior that reflects a dysfunction in the psychological, biological, or development processes underlying mental functioning.” We can directly relate this to what is said in the Times article. Joseph Frascella mentions that addictions are a repetitive behavior seen in the face of negative consequences. Going further to mention that it is a "...desire to continue something you know is bad for you". We can directly compare these two definitions as they both are describing an individual that is exhibiting some sort of dysfunction both cognitively and psychologically related. As we read further we can see this spelled out in more detail through a study done at VA hospital in which methamphetamine addicts who were more likely to relapse within a year were also "less able to complete tasks involving cognitive skills..." Which is in direct support of our definition of a mental disorder as their brains are exhibiting a dysfunction.
* Prompt 2
Their are ample systemic reasons that directly relate to mental health care access. Examples we can list directly from the slides are factors related to expense, debilitation, lack of treatment, limited services for children, adolescents, and those in rural areas, and limited training for primary care providers. As we look through this list (which could easily go on), we can pick out some social determinants of health (SDOH) that have a direct impact on mental health treatment. The first chain I can pick out is from the beginning of our list. Because mental illness can be debilitating and can impact ones ability to work effectively. This in turn could further impact ones access to health insurance. Since mental illness is extremely expensive to treat, the subject may in turn go long periods untreated. This directly relates to the SDOH related to income level, which creates a feedback loop worsening both mental health and ability to work and develop an income.
