:PROPERTIES:
:ID:       809e0aac-88d2-4141-bc4e-24230f0dfbf9
:END:
#+title: No Other Choice
#+subtitle: Park Chan-wook
#+filetags: Movie Reviews

An extremely dense (not uncommon with Park Chan-wook) and intense satire. This movie left much to be processed as I find myself often feeling with this director, so I will likely add more to this review as time goes on. -- First impressions, I enjoyed this film quite a lot. The film does a good job pacing itself and setting each character of significance up adding a higher intensity to many scenes. It can be a quite ridiculous, and often funny, film at times but themes of learning to embrace modernity and family struggles help ground the film which is by no means a knock. More of a selfish thing that stuck with me was definitely the soundtrack. The use of music in this film was fun and intentional. I've noticed Park Chan-wook tends to utilize musical motifs in his work often, which can be very impactful within scenes throughout a film. This movie is no exception. Music seamlessly moves form the soundtrack to being part of the world and vice versa which added much appreciated depth to the movie in a sonic direction. I will definitely be watching this one again in time. 
