:PROPERTIES:
:ID:       c6420f2f-4080-4f1c-a8c6-ad4978e382f0
:END:
#+title: Note Structuring
#+filetags: Memos

#+OPTIONS: toc:nil
#+begin_export latex
\clearpage
#+END_EXPORT

* Purpose
When it comes to note taking I want this to be as intentional and functional as possible. Notes, that I take within this program I believe should serve a purpose. From how I see, node based notes shine best in terms of the quick indexing they provide. This means that they are powerful as tool for studying and researching as they can be quickly referred to at any point. Regardless of where I am.

At the moment of writing this, my note taking is mostly within the context of College. Each course has it's own structure--However, that rarely impacts the structure of ones personal notes. In that way, the structure created here should be applicable to all cases within or outside of the university space. It is effective in all spaces of learning and/or thought.
#+begin_center
 Joel, 2025
#+end_center
* A Time & A Place
A core part of this note taking system is understanding when to use it; Recognizing when it can be valuable, and when it won't be.
** The When Not
What this system isn't, is a catch-all--This is not for writing notes verbatem.
*** On Verbatem Notes
+ "Verbatem" note taking is to be used when learning a topic /and/or/ subject for the first time; When developing your understanding.
+ ~Instruction:~
  + Before a new week of isntruction begins start the week by taking notes, word-for-word, from the textbook
  + This wil help develop a basis of understanding regarding  topics that will be covered in lecture that week.
** The When
This system is the final consolidation of what you've learned throughout the week. It should reflect not only what you learned; but specifically your understanding of the content/topic. It is personalized and a reflection of how your own brain thinks. Notes, that when you look back at them you easily understand them as they are written in your tongue; Written for you.
* The Note Structure
Now that we understand when to use this digital structure--let us now discuss the how.
