:PROPERTIES:
:ID:       52845742-954d-4e2d-89f7-8df41a07b6e3
:END:
#+title: OurHome
#+filetags:Notes
* File Tasks
** TODO Rerference pictures!

* House (Estate)
Eichler home (less glass); estate style with multiple buildings connected by a courtyard; sprawling (1 of which is a gym) separate home for julies mom (give her a golf cart!). mom will take care of farm, dad will assist with animals. front facing wide drive way with fountain(?). SHOW OFF 911s

public facing barn (for slaughter pickup)

selective clearing of forest to block out view of sections of estate; paths interconnect

YOGA HOUSE (glass house; dark wood floor planks; lots of plants (HUMID ASF) next to pool)
* Land Features
** OurFarm
*** Animals (in acquisitional chronological order)
+ Doberman
+ Chickens
  + food and eggs
+ Cows [3]
  + milk and meat (sad)
+ Kittens [2]
  + Shelter or Maine Coon?
+ Belgian Mal. (puppy) ~OR~ Dutch Shepherd
  + ~Our travel dog!~
+ Central Asian Shepherd ~OR~ Tibetan Mastiff

** Garden
*** Contents
+ Herbs
+ Potatoes
+ Lettuce
+ Cucumbers
+ Bitter Melon
+ Watermelon
+ Fruit(?)

** Julie's Mom House

** Pond
*** Animals
** Fence
** Cameras
