:PROPERTIES:
:ID:       96b03afb-2ff9-4b9f-ba72-e5f74f872b90
:END:
#+title: Week_14
[[id:884b87aa-d49c-4404-9662-047dd51e14a5][CTCM2530]]
#+filetags: Notes

* Commercial Seafood
** Key Terms
+ Aquaculture
+ Overfishing
+ Fisheries (fish farms)
+ Net Pens
+ Nutrient Booms
+ Genetic uniformity
+ National Organic Program
** *Aquaculture*
/Fish or shellfish farming in all waters/
+ _Major issues_
  + *overfishing*
  + Illegal fishing
  + *Fisheries (fish farms)* confined spaces
  + Water, land & air pollution
  + Net pens ocean/rivers
    + Sea lice & viruses
    + Nutrient booms
  + *Genetic uniformity*
  + Disease
  + Feed (cheap)
  + Feed for hormone growth
  + Drugs (for disease or pests)
** Wild Fisheries off US ports
+ 2013 National Oceanic and Atmospheric Administration (N.O.A.A.) reported total catch of 9.2 billion pounds of seafood for American ports, beating averages for last 10 years.
** Aquaculture
+ *Aquaculture* -- Also known as fish or shellfish farming -- refers to breeding, rearing, & harvesting of plants & animals in all water environments
+ Freshwater & marine species of fish and shellfish farmed
+ Aquaculture produces food fish, sport fish, bait fish, ornamental fish, crustaceans, mollusks, algae, sea vegetables, & fish eggs
+ 2006, 60% commerical stock overfished
+ 1/2 Seafood eaten worldiwde - including USA - is farm-raised
+ Because harvest from many wild fisheries has peaked globbally, aquaculture meets seafood demands of a growing population
** 1995 Report
+ 1988, USA provided only 2% of world's aquaculture production, or 2.4% of total value
+ US production mostly nonfood items including baitfish, ornamentals, & stock for fisheries enhancement & stocking "pay" lakes (recreational fishing)
+ US freshwater aquaculture made significant gains since 1980s
+ Catfish production in ponds in Southeast, particularly Mississippi, & production of trout, particularly in Idaho & CA
+ Marine aquaculture fared much less well
+ Considerable R & D underway for marine aqauculture, but commercial success limited
+ Environmental constraints, institutional regulations, & pubic perception against it
+ 1980s per capita consumption of fish increased a lot in US in despite consumer price index for fish increasing more rapidly than other foods
+ Diet-conscious public 1980s increase amount of fish in diet even though relative price of fish increased
+ Per capita consumption fish increased 22% from 1980 to 1989
+ Consumer price index for fish increased 64% versus 52.5% for all other foods
+ 1988 USA marine aquaculture production
  + $87 million
+ Low production & increasing consumption caused USA to remain dependent upon imports
+ During past decade, imports accounted for about 1/2 to 2/3 of edible seafood consumed US
** Aquaculture Facts!
+ 1/2 food eaten worl & in US is farm-raised, not wild catch
+ 70% of world's salmon is farmed
+ *US National Organic Standards Board* will begin organix aquaculture certification in 2016
+ China produces 61.6% total aquaculture
+ US produced only 2% total global aquaculture!
+ 2012 US sea commericial fishermen landed 9.6 billion lbs seafood or $5.1 billion
+ 20% fish caught was for pet food, fish meal & oil
+ 2012 avg. person US ate 14.4lbs fish & shellfish
+ US imports 80% of its seafood, a trade deficit of over $8 billion
** Depleted stocks of wild fish
+ Asian Development Bank loaned over $33 million to govt program in Indonesia promote community-managed freshwater fish farms
+ Fish pens
** Farmed vs. Wild
+ _Farmed fish_
  + Fish feed (smaller fish & pellets soymeal)
  + 1996 farmed salmon passed wild salmon in sales. Today 70% salmon farmed
  + Nutrient content: fattier, more sodim, 13% vitamin C, hald iron of wild salmon
  + Norway, Chile, Scotland, Canada
  + Problems: PCBs, chemicals, sea lice
+ _Wild fish_
  + Natural food chain
  + Salmon 3rd most popular seafood behind shrimp & canned tuna pas 10 years
  + Nutrient content: less fat, less sodium, no vitamin C, twice iron of farmed salmon
  + Everywhere
  + Problems: Declining fisheries, higher water temperatures
** 3 Major problems fish farming in ocean
1. Fish farming facilities located in fragile waters, with construction & operating practices, including feeding & medicating the fish, adverse impacts on the waterbodies
   + Excess food, & antibiotics contaminate nearby waters & smother organisms sch as shellfish
   + Floating pens anchored to the seabed--has detrimental effects on sea bottom, & maintenance introduces toxic chemicals such as pesticides into water
   + Asia shrimp farming destroyed huge acreages of important mangroves, eliminating habitat & fouling water
   + Israel halted fish farming near Red Sea damage to coral reefs. But it promotes fish farming in desert using brackish groundwater. The water, enriched by waste from the aquaculture operation reused in crop irrigation
2. Detrimental effect from escapees from farms on wild species, as farmed fish carry diseases & parasites & compete with wild fish for food
   + Farm fish bred to be voracious feeders, so escapees may outcompete wild fish for food & mating
   + Farm-raised fish less healthy, delete gene pool interbreeding wild stocks
   + CA banned raising salmon in state waters to protect native stocks; established regulatory measures stop pollution, drugs, & chemicals posed by fish farming; & banned transgenic fish--genetically modified
3. Farming carnivorous species, such as salmon & shrimp, requires other species be fished to provide food for the farmed stock in a greater proportion than amount
   + For 1 kilogram of farmed fish at least 3 kilograms of food fish. This reduces forage species populations & lessens amount food for wild fish
   + Safety of feed used in fish farming, ex. China sold unadultered fish protein
** Aquaculture farm techniques
+ Pond culture: earthen ponds freshwater fish, shrimp
+ Cage culture: enclosed cages submerged
+ Recirculating systems: fish, shellfish, and/or plant life raised in "close-loop" systems filter & recycle water & waste
+ Integrated multitrophic aquaculture – several species raised together allows 1 species’ by-products to feed another species
+ Integrated agriculture & aquaculture –ponds or recirculating systems used to raise both seafood & other organisms (example, fish & lettuce)
+ Shellfish farming techniques include grow-out in bags placed in tidelands, suspended culture, and “rack and bag” grow-out
** Fish pens
+ Aquaculture 2013
+ fish farming & stocking sea creatures in wild bodies of water — only made a small increase to account for 5 % of the American catch
** Issues
+ China dominates market for farmed seafood
+ China’s share of global production from aquaculture 77 x larger than USA in 2011
+ Proponents US domestic fish farming advocate modest increase in aquaculture efforts
+ US govt goal doubling US aquaculture would result in 50,000 domestic jobs & $1 billion of new value
** Organic Seafood
+ USDA’s *National Organic Program* developing organic standards for a decade
+ Intense debate environmentalists, scientists & producers about what should & should not be allowed
+ Organic aquaculture standards that National Organic Standards Board contemplating available public comment summer 2015
+ Certification process could begin in 2016, with first USDA certified organic fish in 2017
+ Most organic foods & environmental groups consider standards watered down version of organic standards for other foods
* Transgenic, Biotechnology & Food Politics
** Key Terms
+ Genetically Modified Organism (GMO)
+ Transgenic
+ Biotechnology
+ US Dept of Agriculture
+ Precautionary principle
+ Ingredient Labeling
** *Genetically Modified Organism (GMO)*: Food
** Food Chemistry
+ *Transgenic*
  + A gene or genetic material transferred naturally or by genetic engineering fro one organism to another
+ Food *Biotechnology*
  + Utilizes knowledge of plant science & genetics to move genes for valuable traits from one plant to another
  + Increases speed & precision to improve food traits & production practices
** _International Food Information Council Foundation Fact Sheet: Benefits of Food Biotechnology_
+ With rising global population & rising food prices, the task of feeding the world is going to become more challenging and is just one reason to capitalize on the benefits of biotechnology.
+ Use of biotech plants can produce more food on less land, by reducing the amount of crops lost to disease and pests. It can reduce $CO_2$ emissions from the farming process, the amount pesticides used to produce foods, and in the future, the amount of water needed to grow crops.
+ Researchers are also enhancing nutritional value of foods.
** Fact Sheet: Benefits of Food Biotechnology
+ Agriculture Biotechnology Benefits the Engiorment
  + Certain biotech foods designed to resist pests and diseases, allowing farmers to use _ _ _, such as pesticides and herbicides, while still maintaining a healthy, high-yielding crop.
+ Reduction in chemical usage beneficial for water & wildlife, as well as for those consumers who may worry about ingesting chemicals when eating fruits & vegetables
+ Biotech crops require less plowing to control weeds since many are modified to be inherently resistant to herbicides
+ Less plowing releass less carbon dioxide, or $CO_2$, into the environment compared to conventional tillage and helps to sustain habitats beneficial for insects, birds, and other animals
+ Biotechnology can help to limit deforestation because crops produce higher yield & require less acreage to produce the same amount of product. Researchers working on drought resistance seeds to grow food in less dry areas
** GMO benefits
+ 70% US food contains GM
+ GM food (made in a lab) only available 33 years
+ Lowers price of food
+ Supports Claim:
  + GM can make crops resistant to viruses, fungi & bacterial growth
  + Crops grow faster & bigger
  + Pest resistant & thus need less pesticides
  + Tolerate extreme weather
  + Some can add vitamins & minerals
** US Dept of Agriculture (USDA)
+ Law requires food companies sell safe food
+ Food companies are not required to ask USDA for GM approval but can ask for it
+ USDA can determine if a food is unsafe
+ USDA sets standards for what is an organic food and lebls it
** Hell no GMO
+ Public has been worried about safety of GM foods since scientists at Univ. of Washington developed 1st genetically modified tobacco plants in the 1970s
+ Mid-1990s, when 1st GM crops reached the market, Greenpeace, Sierra Club, Ralph Nader, Prince Charles & celebrity chefs took highly visible stands against them
** Anti-GMO rebuttal
+ 2013: 10% world's cropland includes GM plants
  + 4 nations: USA, Canada, Brazil, Argentina--grow 90% GM crops
+ European Union fierce opponents
  + 1997 European survey 69% Austrian public saw serious risks in GM foods, compared with only 14% of Americans
+ Latin American, African, Asian nations, not interested GM
** Hell no GMO pt.2
+ Nearly all corn & soybeans grown in USA genetically modified, but only 2 GM crops, Monsanto's MON810 maize and BASF's Amflora potato, are accepted in the European Union
+ 8 EU nations banneed GM crops outright
+ Throughout Asia, including in India & China, govts have yet to approve most GM crops, including an insect-resistant rice that produces higher yields with less pesticide
+ In Africa, where millions go hungry, several nations have refused to import GM foods in spite of their lower costs (the result of higher yields and a reduced need for water and pesticides)
** *Precautionary Principle*
+ Europeans who oppose genetic modification support "the precautionary principle"
  + given the kind of catastrophe that would emerge from accidental toxic, invasive GM crop on the world, GM efforts should be shut down until technology proved absolutely safe
+ 2013--at least 20 USA states considering GM-labeling bills, all failed. Food companies and food growers, GM companies oppose state labeling, prefer USDA rules
** CA Prop 37 (2012)
+ _Mandatory Labeling of Genetically Engineered Food Initiative_
+ Voters defeated it 6.4 million (51.4%) to 6.1 million
+ If proposition 37 has been approved, it would have:
  + Required labeling on raw or processed food offered for sale to consumers if the food is made from plants or animals with genetic material changed in specified ways
  + Prohibited labeling or advertising such food as "natural"
  + Long list of exemptions
+ Supporters of Prop 37 spent $8.7 million
+ Opponents spent $45.6 milloin
** Food Politics
+ Food industry politics
+ Industrial food
+ Lobbyist
+ Food Wars:
  + Industrial production
  + Mono-genetic food
  + *Ingredient labeling*
  + govt subsidies GMO
  + healthy food
